name: Execução Pipeline n1
'on':
  workflow_dispatch: null
jobs:
  e2e-tests:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
        
      - name: Instalando Cypress
        run: npm install
        


